# This file was generated by GoReleaser. DO NOT EDIT.
cask "sq" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "19bf7d9c53be1661f0508ec5acd129976a5a0eec94d3352e468676d412078e84"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "87ffb424c3de42bb072e23666b0bd4c085a3e17e6784df2054c2233d0f1b8907"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "919db4279594cc841b7a6529daf321f29cc00ee7163ba730e5a3ccd614150a5e"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "814ebe606cb952eeeaf9ae5a685096a6b70c9bbd7ee761959bcd7164a09fada3"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sq"
  desc "Local AI routing gateway — one OpenAI-compatible endpoint across 40+ providers, format translation, quota tracking, cost analytics."
  homepage "https://github.com/KHANHDANGBMT/ShareQuota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sq"
  binary "sqctl"

  # No zap stanza required

  caveats <<~EOS
    Start the gateway (foreground, auto-opens dashboard):
      sqctl
    Dashboard: http://localhost:20501/dashboard
    Default password: 123456 (change on first login → /dashboard/profile)
  EOS
end
