# This file was generated by GoReleaser. DO NOT EDIT.
cask "sq" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "7db9776ba156589e6a0d305863d9a85c91f5cafee94fba0e234387f7e80dcd92"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9e1fde5d453bcc01be776db3d86c9804f0ab218f58eca63d2f351d3b6f35211"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "348e5b1788c306e6fa6fbc94ae958f26a8e4ccdb77f182ee96e435bfaba78398"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c39df72e68a69e98329c57b6adff16c9fb612185df5ddfa46d6a3e71d1f840d3"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sq"
  desc "Local AI routing gateway — one OpenAI-compatible endpoint across 40+ providers, format translation, quota tracking, cost analytics."
  homepage "https://github.com/KHANHDANGBMT/ShareQuota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sq"
  binary "sqctl"

  # No zap stanza required

  caveats <<~EOS
    Start the gateway (foreground, auto-opens dashboard):
      sqctl
    Dashboard: http://localhost:20501/dashboard
    Default password: 123456 (change on first login → /dashboard/profile)
  EOS
end
