# This file was generated by GoReleaser. DO NOT EDIT.
cask "sq" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "08e39a07ac7f61eb2925af4ac0e13c65dc6b946d541b3de390380ee84c536c6a"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "639149b8511d75b8ad235816d8851e830e53ebd4a993336f7a96bd241f58f75a"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "634ec95ccadd2e0c8a7ba8084f3bf10299e8145d81f297e86139fc7dfaddc194"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b283b4d5493b3cc9bc28d901d478bb23f279a31fa51222abe7ec147feb329718"
      url "https://github.com/KHANHDANGBMT/ShareQuota/releases/download/v#{version}/ShareQuota_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sq"
  desc "Local AI routing gateway — one OpenAI-compatible endpoint across 40+ providers, format translation, quota tracking, cost analytics."
  homepage "https://github.com/KHANHDANGBMT/ShareQuota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sq"
  binary "sqctl"

  # No zap stanza required

  caveats <<~EOS
    Start the gateway (foreground, auto-opens dashboard):
      sqctl
    Dashboard: http://localhost:20501/dashboard
    Default password: 123456 (change on first login → /dashboard/profile)
  EOS
end
